#! /bin/sh

bspc config border_width        6

MAINCOLOR="#444851"

bspc config focused_border_color "$MAINCOLOR"
bspc config normal_border_color "$MAINCOLOR"
bspc config active_border_color "$MAINCOLOR"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a \* floating=on
bspc rule -a tint2 manage=off

bspc config right_padding 36

bspc monitor -d 1 2 3
#bspc desktop -f 3 

sleep 1 && tint2 &
